### ISSUE TITLE
Doesnot work on my machine 

### ISSUE THREAD

**Issue by animeshchaudhri** [shreverr/node-rizz#1]
pls fix
#apna college

**Comment by shreverr** [comment]
Don't spam or I will ban you

**Comment by animeshchaudhri** [comment]
uban or gay

**Comment by KartikeyBartwal** [comment]
This is no appropriate way to contribute to open source. Kindly apologise or @shreverr, please ban him. He seems gay

**Comment by shreverr** [comment]
> This is no appropriate way to contribute to open source. Kindly apologise or @shreverr, please ban him. He seems gay

Huh ╰（‵□′）╯
